name: Docker Image CI

on:
  release:
    types:
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the (development) Docker image
      env:
          GITHUB_REF: ${{ github.ref }}
      run: docker build --target development -t cricdatabase/angular:${GITHUB_REF/refs\/tags\/v/}-development .
    - name: Build the (production) Docker image
      env:
          GITHUB_REF: ${{ github.ref }}
          CRIC_DOMAIN: "https://database.cric.com.br"
          CRIC_API_DOMAIN: "https://database.cric.com.br"
          CRIC_EMAIL: "cric@ufop.edu.br"
          CRIC_PLAYGROUND: false
      run: docker build --build-arg CRIC_DOMAIN --build-arg CRIC_API_DOMAIN --build-arg CRIC_EMAIL --build-arg CRIC_PLAYGROUND --target production -t cricdatabase/angular:${GITHUB_REF/refs\/tags\/v/}-production .
    - name: Build the (playground) Docker image
      env:
          GITHUB_REF: ${{ github.ref }}
          CRIC_DOMAIN: "https://playground.database.cric.com.br"
          CRIC_API_DOMAIN: "https://playground.database.cric.com.br"
          CRIC_EMAIL: "cric@ufop.edu.br"
          CRIC_PLAYGROUND: true
      run: docker build --build-arg CRIC_DOMAIN --build-arg CRIC_API_DOMAIN --build-arg CRIC_EMAIL --build-arg CRIC_PLAYGROUND --target production -t cricdatabase/angular:${GITHUB_REF/refs\/tags\/v/}-playground .
    - name: Login into DockerHub
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - name: Push the (development) Docker image
      env:
          GITHUB_REF: ${{ github.ref }}
      run: docker push cricdatabase/angular:${GITHUB_REF/refs\/tags\/v/}-development
    - name: Push the (production) Docker image
      env:
          GITHUB_REF: ${{ github.ref }}
      run: docker push cricdatabase/angular:${GITHUB_REF/refs\/tags\/v/}-production
    - name: Push the (playground) Docker image
      env:
          GITHUB_REF: ${{ github.ref }}
      run: docker push cricdatabase/angular:${GITHUB_REF/refs\/tags\/v/}-playground
      
